export const project__data: TProject[] = [
  {
    name: "Les francophones",
    url: "https://lesfrancophones.com",
    date: {
      start: "september 2020",
      end: "january 2022",
    },
    tech: ["wordpress"],
    git_repo: null,
    preview: null,
    isPro: true,
  },
  {
    name: "Autofunnel",
    url: "https://autofunnel.io",
    date: {
      start: "january 2022",
      end: "february 2022",
    },
    tech: ["next.js", "craft js", "redux", "next auth"],
    git_repo: null,
    preview: null,
    isPro: true,
  },
  {
    name: "Montreautomatique",
    url: "https://montreautomatique.com",
    date: {
      start: "february 2022",
      end: "august 2022",
    },
    tech: ["wordpress"],
    git_repo: null,
    preview: null,
    isPro: true,
  },
  {
    name: "Conteenium",
    url: "https://conteenium.com",
    date: {
      start: "february 2022",
      end: "august 2022",
    },
    tech: ["wordpress"],
    git_repo: null,
    preview: "",
    isPro: true,
  },
  {
    name: "Maisonetmoi",
    url: "https://maisonetmoi.fr",
    date: {
      start: "november 2022",
      end: "february 2023",
    },
    tech: ["wordpress"],
    git_repo: null,
    preview: "",
    isPro: true,
  },
  {
    name: "Facebook2-0",
    url: "https://facebook2-by-rtn.vercel.app",
    date: {
      start: "june 2021",
      end: null,
    },
    tech: [
      "next.js",
      "mysql2",
      "axios",
      "swr",
      "tailwindcss",
      "framer-motion",
      "jwt",
      "vercel",
    ],
    git_repo: "https://github.com/randriamampionona/facebook2.0",
    preview: "/assets/preview/Facebook2-0.png",
    isPro: false,
  },
  {
    name: "Rohy-server",
    url: "https://rohy-server.vercel.app",
    date: {
      start: "november 2022",
      end: null,
    },
    tech: ["node.js", "express", "bcrypt", "jwt", "mysql", "mvola", "vercel"],
    git_repo: "https://github.com/randriamampionona/rohy_server",
    preview: "/assets/preview/Rohy-server.png",
    isPro: false,
  },
  {
    name: "Rohy",
    url: "https://rohy.vercel.app",
    date: {
      start: "october 2022",
      end: null,
    },
    tech: [
      "next.js",
      "axios",
      "cloudinary",
      "firebase",
      "firebase-admin",
      "framer-motion",
      "nookies",
      "react-firebase-hooks",
      "tailwindcss",
      "swr",
      "vercel",
    ],
    git_repo: "https://github.com/randriamampionona/rohy",
    preview: "/assets/preview/Rohy.png",
    isPro: false,
  },
  {
    name: "Mirentymg",
    url: "https://mirentymg.vercel.app",
    date: {
      start: "mars 2023",
      end: "may 2023",
    },
    tech: [
      "next.js",
      "axios",
      "firebase",
      "firebase-admin",
      "tailwindcss",
      "swr",
      "vercel",
    ],
    git_repo: "https://github.com/randriamampionona/mirenty",
    preview: "/assets/preview/Mirentymg.png",
    isPro: false,
  },
  {
    name: "Hi-tafa",
    url: "https://hi-tafa.vercel.app",
    date: {
      start: "april 2023",
      end: null,
    },
    tech: [
      "next.js v13",
      "axios",
      "firebase",
      "firebase-admin",
      "tailwindcss",
      "swr",
      "vercel",
    ],
    git_repo: "https://github.com/randriamampionona/hi-tafa",
    preview: "/assets/preview/Hi-tafa.png",
    isPro: false,
  },
  {
    name: "Tubi",
    url: "https://tubi.vercel.app",
    date: {
      start: "jully 2023",
      end: null,
    },
    tech: [
      "next.js v13",
      "typescript",
      "tailwindcss",
      "firebase",
      "firebase-admin",
      "axios",
      "vercel",
    ],
    git_repo: "https://github.com/randriamampionona/tubi",
    preview: "/assets/preview/Tubi.png",
    isPro: false,
  },
  {
    name: "Groove-music-clone",
    url: "https://groove-music-clone.vercel.app",
    date: {
      start: "december 2023",
      end: null,
    },
    tech: [
      "next.js v14",
      "typescript",
      "next-themes",
      "shadcn",
      "clerk",
      "zustand",
      "tailwindcss",
      "vercel",
    ],
    git_repo: "https://github.com/randriamampionona/hi-tafa",
    preview: "/assets/preview/Groove-music-clone.png",
    isPro: false,
  },
];
